cellIdPreamble: "cell-"
gradientMode: "hue"

cells:
  raw_in:
    dataRef: "rabbitmq_queue.raw_in"
    label:
      separator: "colon"
      units: "per second"

  raw_out:
    dataRef: "rabbitmq_queue.raw_out"
    label:
      separator: "colon"
      units: "per second"
  
  raw_size:
    dataRef: "rabbitmq_queue.raw_size"
    label:
      separator: "colon"